apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: pns3l23hl-go 
  janus-idp.io/tekton: pns3l23hl-go
  backstage.io/kubernetes-id: pns3l23hl-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pns3l23hl-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  