apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: pns3l23hl-go
  janus-idp.io/tekton: pns3l23hl-go
  backstage.io/kubernetes-id: pns3l23hl-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pns3l23hl-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
