apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: pns3l23hl-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pns3l23hl-go 
  name: pns3l23hl-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: pns3l23hl-go 
